#!/bin/bash
BATLEVEL="$(upower -i $(upower -e | grep battery) | grep percentage | awk '{print substr($2, 0, length($2)-1)}')"
BATLEVELLINE="$(echo 0 $BATLEVEL 100 | spark | awk '{print substr($1, 2, 1)}')"
echo "[$BATLEVEL%] $BATLEVELLINE"
